//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class EventNameWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("EventName");
		L.RegConstant("EVENT_CS_NET_START", 0);
		L.RegConstant("EVENT_CS_NET_CONNECTED", 1);
		L.RegConstant("EVENT_CS_NET_CLOSE", 2);
		L.RegConstant("EVENT_CS_NET_RECEIVE", 3);
		L.RegConstant("EVENT_CS_UI_START", 65536);
		L.RegConstant("EVENT_CS_UI_SHOW_UI", 65537);
		L.RegConstant("EVENT_CS_UI_REFRESH_LOADING_UI", 65538);
		L.RegConstant("EVENT_CS_UI_OPEN_TIPS_UI", 65539);
		L.RegConstant("EVENT_CS_UI_OPEN_INITFORM_UI", 65540);
		L.RegConstant("EVENT_CS_UI_TIPS_CALLBACK", 65541);
		L.RegConstant("EVENT_CS_GAME_START", 131072);
		L.RegConstant("EVENT_CS_GAME_MOVE_DIRECTION", 131073);
		L.RegConstant("EVENT_CS_GAME_MOVE_END", 131074);
		L.RegConstant("EVENT_CS_GAME_ENTITY_SHOW", 131075);
		L.RegConstant("EVENT_CS_GAME_ENTITY_HIDE", 131076);
		L.EndStaticLibs();
	}
}

