//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_Procedure_ProcedureBaseWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameFramework.Procedure.ProcedureBase), typeof(GameFramework.Fsm.FsmState<GameFramework.Procedure.IProcedureManager>));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}
}

