//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class GameFramework_BaseEventArgsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(GameFramework.BaseEventArgs), typeof(GameFramework.GameFrameworkEventArgs));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("Id", new LuaCSFunction(get_Id), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Id(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			GameFramework.BaseEventArgs obj = (GameFramework.BaseEventArgs)o;
			int ret = obj.Id;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Id on a nil value");
		}
	}
}

