//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SuperScrollView_LoopListViewInitParamWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SuperScrollView.LoopListViewInitParam), typeof(System.Object));
		L.RegFunction("CopyDefaultInitParam", new LuaCSFunction(CopyDefaultInitParam));
		L.RegFunction("New", new LuaCSFunction(_CreateSuperScrollView_LoopListViewInitParam));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("mDistanceForRecycle0", new LuaCSFunction(get_mDistanceForRecycle0), new LuaCSFunction(set_mDistanceForRecycle0));
		L.RegVar("mDistanceForNew0", new LuaCSFunction(get_mDistanceForNew0), new LuaCSFunction(set_mDistanceForNew0));
		L.RegVar("mDistanceForRecycle1", new LuaCSFunction(get_mDistanceForRecycle1), new LuaCSFunction(set_mDistanceForRecycle1));
		L.RegVar("mDistanceForNew1", new LuaCSFunction(get_mDistanceForNew1), new LuaCSFunction(set_mDistanceForNew1));
		L.RegVar("mSmoothDumpRate", new LuaCSFunction(get_mSmoothDumpRate), new LuaCSFunction(set_mSmoothDumpRate));
		L.RegVar("mSnapFinishThreshold", new LuaCSFunction(get_mSnapFinishThreshold), new LuaCSFunction(set_mSnapFinishThreshold));
		L.RegVar("mSnapVecThreshold", new LuaCSFunction(get_mSnapVecThreshold), new LuaCSFunction(set_mSnapVecThreshold));
		L.RegVar("mItemDefaultWithPaddingSize", new LuaCSFunction(get_mItemDefaultWithPaddingSize), new LuaCSFunction(set_mItemDefaultWithPaddingSize));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSuperScrollView_LoopListViewInitParam(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SuperScrollView.LoopListViewInitParam obj = new SuperScrollView.LoopListViewInitParam();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SuperScrollView.LoopListViewInitParam.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int CopyDefaultInitParam(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SuperScrollView.LoopListViewInitParam o = SuperScrollView.LoopListViewInitParam.CopyDefaultInitParam();
			ToLua.PushObject(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mDistanceForRecycle0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mDistanceForRecycle0;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForRecycle0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mDistanceForNew0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mDistanceForNew0;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForNew0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mDistanceForRecycle1(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mDistanceForRecycle1;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForRecycle1 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mDistanceForNew1(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mDistanceForNew1;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForNew1 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mSmoothDumpRate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mSmoothDumpRate;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mSmoothDumpRate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mSnapFinishThreshold(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mSnapFinishThreshold;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mSnapFinishThreshold on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mSnapVecThreshold(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mSnapVecThreshold;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mSnapVecThreshold on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_mItemDefaultWithPaddingSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float ret = obj.mItemDefaultWithPaddingSize;
			LuaDLL.lua_pushnumber(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mItemDefaultWithPaddingSize on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mDistanceForRecycle0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mDistanceForRecycle0 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForRecycle0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mDistanceForNew0(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mDistanceForNew0 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForNew0 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mDistanceForRecycle1(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mDistanceForRecycle1 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForRecycle1 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mDistanceForNew1(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mDistanceForNew1 = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mDistanceForNew1 on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mSmoothDumpRate(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mSmoothDumpRate = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mSmoothDumpRate on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mSnapFinishThreshold(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mSnapFinishThreshold = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mSnapFinishThreshold on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mSnapVecThreshold(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mSnapVecThreshold = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mSnapVecThreshold on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_mItemDefaultWithPaddingSize(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			SuperScrollView.LoopListViewInitParam obj = (SuperScrollView.LoopListViewInitParam)o;
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 2);
			obj.mItemDefaultWithPaddingSize = arg0;
			return 0;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index mItemDefaultWithPaddingSize on a nil value");
		}
	}
}

