//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityGameFramework_Runtime_LoadSceneFailureEventArgsWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityGameFramework.Runtime.LoadSceneFailureEventArgs), typeof(GameFramework.Event.GameEventArgs));
		L.RegFunction("Create", new LuaCSFunction(Create));
		L.RegFunction("Clear", new LuaCSFunction(Clear));
		L.RegFunction("New", new LuaCSFunction(_CreateUnityGameFramework_Runtime_LoadSceneFailureEventArgs));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("EventId", new LuaCSFunction(get_EventId), null);
		L.RegVar("Id", new LuaCSFunction(get_Id), null);
		L.RegVar("SceneAssetName", new LuaCSFunction(get_SceneAssetName), null);
		L.RegVar("ErrorMessage", new LuaCSFunction(get_ErrorMessage), null);
		L.RegVar("UserData", new LuaCSFunction(get_UserData), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateUnityGameFramework_Runtime_LoadSceneFailureEventArgs(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				UnityGameFramework.Runtime.LoadSceneFailureEventArgs obj = new UnityGameFramework.Runtime.LoadSceneFailureEventArgs();
				ToLua.PushSealed(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: UnityGameFramework.Runtime.LoadSceneFailureEventArgs.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Create(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			GameFramework.Scene.LoadSceneFailureEventArgs arg0 = (GameFramework.Scene.LoadSceneFailureEventArgs)ToLua.CheckObject<GameFramework.Scene.LoadSceneFailureEventArgs>(L, 1);
			UnityGameFramework.Runtime.LoadSceneFailureEventArgs o = UnityGameFramework.Runtime.LoadSceneFailureEventArgs.Create(arg0);
			ToLua.PushSealed(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Clear(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			UnityGameFramework.Runtime.LoadSceneFailureEventArgs obj = (UnityGameFramework.Runtime.LoadSceneFailureEventArgs)ToLua.CheckObject<UnityGameFramework.Runtime.LoadSceneFailureEventArgs>(L, 1);
			obj.Clear();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_EventId(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, UnityGameFramework.Runtime.LoadSceneFailureEventArgs.EventId);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Id(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityGameFramework.Runtime.LoadSceneFailureEventArgs obj = (UnityGameFramework.Runtime.LoadSceneFailureEventArgs)o;
			int ret = obj.Id;
			LuaDLL.lua_pushinteger(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index Id on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_SceneAssetName(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityGameFramework.Runtime.LoadSceneFailureEventArgs obj = (UnityGameFramework.Runtime.LoadSceneFailureEventArgs)o;
			string ret = obj.SceneAssetName;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index SceneAssetName on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ErrorMessage(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityGameFramework.Runtime.LoadSceneFailureEventArgs obj = (UnityGameFramework.Runtime.LoadSceneFailureEventArgs)o;
			string ret = obj.ErrorMessage;
			LuaDLL.lua_pushstring(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index ErrorMessage on a nil value");
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_UserData(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityGameFramework.Runtime.LoadSceneFailureEventArgs obj = (UnityGameFramework.Runtime.LoadSceneFailureEventArgs)o;
			object ret = obj.UserData;
			ToLua.Push(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index UserData on a nil value");
		}
	}
}

