//this source code was auto-generated by tolua#, do not modify it
using System;
using Deer;
using LuaInterface;

public class UnityGameFramework_Runtime_SceneComponentWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(UnityGameFramework.Runtime.SceneComponent), typeof(UnityGameFramework.Runtime.GameFrameworkComponent));
		L.RegFunction("SceneIsLoaded", new LuaCSFunction(SceneIsLoaded));
		L.RegFunction("GetLoadedSceneAssetNames", new LuaCSFunction(GetLoadedSceneAssetNames));
		L.RegFunction("SceneIsLoading", new LuaCSFunction(SceneIsLoading));
		L.RegFunction("GetLoadingSceneAssetNames", new LuaCSFunction(GetLoadingSceneAssetNames));
		L.RegFunction("SceneIsUnloading", new LuaCSFunction(SceneIsUnloading));
		L.RegFunction("GetUnloadingSceneAssetNames", new LuaCSFunction(GetUnloadingSceneAssetNames));
		L.RegFunction("HasScene", new LuaCSFunction(HasScene));
		L.RegFunction("LoadScene", new LuaCSFunction(LoadScene));
		L.RegFunction("UnloadScene", new LuaCSFunction(UnloadScene));
		L.RegFunction("SetSceneOrder", new LuaCSFunction(SetSceneOrder));
		L.RegFunction("GetSceneName", new LuaCSFunction(GetSceneName));
		L.RegFunction("LoadSceneEx", new LuaCSFunction(LoadSceneEx));
		L.RegFunction("__eq", new LuaCSFunction(op_Equality));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.RegVar("MainCamera", new LuaCSFunction(get_MainCamera), null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SceneIsLoaded(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.SceneIsLoaded(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLoadedSceneAssetNames(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string[] o = obj.GetLoadedSceneAssetNames();
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				System.Collections.Generic.List<string> arg0 = (System.Collections.Generic.List<string>)ToLua.CheckObject(L, 2, TypeTraits<System.Collections.Generic.List<string>>.type);
				obj.GetLoadedSceneAssetNames(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityGameFramework.Runtime.SceneComponent.GetLoadedSceneAssetNames");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SceneIsLoading(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.SceneIsLoading(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetLoadingSceneAssetNames(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string[] o = obj.GetLoadingSceneAssetNames();
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				System.Collections.Generic.List<string> arg0 = (System.Collections.Generic.List<string>)ToLua.CheckObject(L, 2, TypeTraits<System.Collections.Generic.List<string>>.type);
				obj.GetLoadingSceneAssetNames(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityGameFramework.Runtime.SceneComponent.GetLoadingSceneAssetNames");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SceneIsUnloading(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.SceneIsUnloading(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetUnloadingSceneAssetNames(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 1)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string[] o = obj.GetUnloadingSceneAssetNames();
				ToLua.Push(L, o);
				return 1;
			}
			else if (count == 2)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				System.Collections.Generic.List<string> arg0 = (System.Collections.Generic.List<string>)ToLua.CheckObject(L, 2, TypeTraits<System.Collections.Generic.List<string>>.type);
				obj.GetUnloadingSceneAssetNames(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityGameFramework.Runtime.SceneComponent.GetUnloadingSceneAssetNames");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int HasScene(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			bool o = obj.HasScene(arg0);
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadScene(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				obj.LoadScene(arg0);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<int>(L, 3))
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				int arg1 = (int)LuaDLL.lua_tointeger(L, 3);
				obj.LoadScene(arg0, arg1);
				return 0;
			}
			else if (count == 3 && TypeChecker.CheckTypes<object>(L, 3))
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				obj.LoadScene(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				int arg1 = (int)LuaDLL.luaL_checkinteger(L, 3);
				object arg2 = ToLua.ToVarObject(L, 4);
				obj.LoadScene(arg0, arg1, arg2);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityGameFramework.Runtime.SceneComponent.LoadScene");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int UnloadScene(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				obj.UnloadScene(arg0);
				return 0;
			}
			else if (count == 3)
			{
				UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
				string arg0 = ToLua.CheckString(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				obj.UnloadScene(arg0, arg1);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: UnityGameFramework.Runtime.SceneComponent.UnloadScene");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetSceneOrder(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checkinteger(L, 3);
			obj.SetSceneOrder(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int GetSceneName(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			string o = UnityGameFramework.Runtime.SceneComponent.GetSceneName(arg0);
			LuaDLL.lua_pushstring(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LoadSceneEx(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 4);
			UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)ToLua.CheckObject<UnityGameFramework.Runtime.SceneComponent>(L, 1);
			string arg0 = ToLua.CheckString(L, 2);
			int arg1 = (int)LuaDLL.luaL_checkinteger(L, 3);
			object arg2 = ToLua.ToVarObject(L, 4);
			obj.LoadSceneEx(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_MainCamera(IntPtr L)
	{
		object o = null;

		try
		{
			o = ToLua.ToObject(L, 1);
			UnityGameFramework.Runtime.SceneComponent obj = (UnityGameFramework.Runtime.SceneComponent)o;
			UnityEngine.Camera ret = obj.MainCamera;
			ToLua.PushSealed(L, ret);
			return 1;
		}
		catch(Exception e)
		{
			return LuaDLL.toluaL_exception(L, e, o, "attempt to index MainCamera on a nil value");
		}
	}
}

