//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class zFrame_UI_Joystick_JoystickEventWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(zFrame.UI.Joystick.JoystickEvent), typeof(UnityEngine.Events.UnityEvent<UnityEngine.Vector2>));
		L.RegFunction("New", new LuaCSFunction(_CreatezFrame_UI_Joystick_JoystickEvent));
		L.RegFunction("__tostring", new LuaCSFunction(ToLua.op_ToString));
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreatezFrame_UI_Joystick_JoystickEvent(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				zFrame.UI.Joystick.JoystickEvent obj = new zFrame.UI.Joystick.JoystickEvent();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: zFrame.UI.Joystick.JoystickEvent.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

