---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Admin.
--- DateTime: 2021/12/17 8:14
---
---@class ScriptWaitBattleInit:SceneScriptBase
ScriptWaitBattleInit = Class("ScriptWaitBattleInit",SceneScriptBase)


return ScriptWaitBattleInit