
---================================================
---描 述 : 
---作 者 : Admin 
---创建时间 : 2021-12-12 20-09-03 
---修改作者 : Admin 
---修改时间 : 2021-12-12 20-09-03 
---版 本 : $Version 
---===============================================
ScrollGridItem = ScrollGridItem --Assets/Deer/Asset/UI/UIPrefab/UIBag/UIBagPanel.prefab
---@class ScrollGridItem:UIBaseClass
--------------AutoGenerated--------------
---@field text TMPro.TextMeshProUGUI
--------------Do not modify!-------------
local ScrollGridItem = Class('ScrollGridItem', UIBaseClass)

function ScrollGridItem:OnAwake()
    self.super.OnAwake(self)
    self:RegisterEvent()

end

function ScrollGridItem:OnEnable()
    self.super.OnEnable(self)
    
end

function ScrollGridItem:OnStart()
    self.super.OnStart(self)
    
end

function ScrollGridItem:OnDisable()
    self.super.OnDisable(self)
   
end

function ScrollGridItem:OnDestroy()
    self.super.OnDestroy(self)
    self:UnRegisterEvent()

end

function ScrollGridItem:RegisterEvent()
    
end

function ScrollGridItem:UnRegisterEvent()

end

function ScrollGridItem:Init()

end

function ScrollGridItem:SetItemData(tbInfo, index, row, column)
    Logger.Debug("ScrollListItem_Index:" .. index)
    self.text.text = index
end
-----------------------------logic----------------------------------

-----------------------------event----------------------------------

-----------------------------button----------------------------------
---@param button UIButtonSuper
function ScrollGridItem:OnClickMainBtn(button)

end
return ScrollGridItem
