-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local _M = {}

_M.LANGUAGE_CONFIG = protobuf.Descriptor();
_M.LANGUAGE_CONFIG_ID_FIELD = protobuf.FieldDescriptor();
_M.LANGUAGE_CONFIG_ENGLISH_FIELD = protobuf.FieldDescriptor();
_M.LANGUAGE_CONFIG_SCHINESE_FIELD = protobuf.FieldDescriptor();
_M.LANGUAGE_CONFIG_DATA = protobuf.Descriptor();
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD = protobuf.FieldDescriptor();

_M.LANGUAGE_CONFIG_ID_FIELD.name = "id"
_M.LANGUAGE_CONFIG_ID_FIELD.full_name = ".ConfigData.Language_Config.id"
_M.LANGUAGE_CONFIG_ID_FIELD.number = 1
_M.LANGUAGE_CONFIG_ID_FIELD.index = 0
_M.LANGUAGE_CONFIG_ID_FIELD.label = 1
_M.LANGUAGE_CONFIG_ID_FIELD.has_default_value = false
_M.LANGUAGE_CONFIG_ID_FIELD.default_value = 0
_M.LANGUAGE_CONFIG_ID_FIELD.type = 13
_M.LANGUAGE_CONFIG_ID_FIELD.cpp_type = 3

_M.LANGUAGE_CONFIG_ENGLISH_FIELD.name = "english"
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.full_name = ".ConfigData.Language_Config.english"
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.number = 3
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.index = 1
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.label = 1
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.has_default_value = false
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.default_value = ""
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.type = 9
_M.LANGUAGE_CONFIG_ENGLISH_FIELD.cpp_type = 9

_M.LANGUAGE_CONFIG_SCHINESE_FIELD.name = "schinese"
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.full_name = ".ConfigData.Language_Config.schinese"
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.number = 4
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.index = 2
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.label = 1
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.has_default_value = false
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.default_value = ""
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.type = 9
_M.LANGUAGE_CONFIG_SCHINESE_FIELD.cpp_type = 9

_M.LANGUAGE_CONFIG.name = "Language_Config"
_M.LANGUAGE_CONFIG.full_name = ".ConfigData.Language_Config"
_M.LANGUAGE_CONFIG.nested_types = {}
_M.LANGUAGE_CONFIG.enum_types = {}
_M.LANGUAGE_CONFIG.fields = {_M.LANGUAGE_CONFIG_ID_FIELD, _M.LANGUAGE_CONFIG_ENGLISH_FIELD, _M.LANGUAGE_CONFIG_SCHINESE_FIELD}
_M.LANGUAGE_CONFIG.is_extendable = false
_M.LANGUAGE_CONFIG.extensions = {}
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.name = "items"
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.full_name = ".ConfigData.Language_Config_Data.items"
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.number = 1
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.index = 0
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.label = 3
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.has_default_value = false
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.default_value = {}
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.message_type = _M.LANGUAGE_CONFIG
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.type = 11
_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD.cpp_type = 10

_M.LANGUAGE_CONFIG_DATA.name = "Language_Config_Data"
_M.LANGUAGE_CONFIG_DATA.full_name = ".ConfigData.Language_Config_Data"
_M.LANGUAGE_CONFIG_DATA.nested_types = {}
_M.LANGUAGE_CONFIG_DATA.enum_types = {}
_M.LANGUAGE_CONFIG_DATA.fields = {_M.LANGUAGE_CONFIG_DATA_ITEMS_FIELD}
_M.LANGUAGE_CONFIG_DATA.is_extendable = false
_M.LANGUAGE_CONFIG_DATA.extensions = {}

_M.Language_Config = protobuf.Message(_M.LANGUAGE_CONFIG)
_M.Language_Config_Data = protobuf.Message(_M.LANGUAGE_CONFIG_DATA)

return _M